List<account> listAcc = new list<account>();

        Account acc = new account();
        acc.name = 'baris';
        acc.phone = '987654321';
        listAcc.add(acc);

        Account acc1 = new account();
        acc1.name = 'yaren';
        acc1.phone = '987654321';
        listAcc.add(acc1);

        Account acc2 = new account();
        acc2.name = 'ozan';
        acc2.phone = '987654321';
        listAcc.add(acc2);

        insert listAcc;





