RankHandler rh=new RankHandler();
string prize1=rh.rankPrize(1);
System.debug(prize1);
string prize2=rh.rankPrize(2);
System.debug(prize2);
string prize3=rh.rankPrize(3);
System.debug(prize3);
String prize4=rh.rankPrize(4);
System.debug(prize4);
String prize9=rh.rankPrize(9);
System.debug(prize9);
String prize10=rh.rankPrize(10);
System.debug(prize10);
String prize12=rh.rankPrize(12);
System.debug(prize12);

string prize1s=rh.rankPrizeSwitch(1);
system.debug(prize1s);
